name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
        FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
        FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
        GH_PAT: ${{ secrets.GH_PAT }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        TEAMID: ${{ secrets.TEAMID }}
      run: |
        echo ${{secrets.FASTLANE_ISSUER_ID}} | sed 's/./& /g'
        echo ${{secrets.FASTLANE_KEY}} | sed 's/./& /g'
        echo ${{secrets.FASTLANE_KEY_ID}} | sed 's/./& /g'
        echo ${{secrets.GH_PAT}} | sed 's/./& /g'
        echo ${{secrets.MATCH_PASSWORD}} | sed 's/./& /g'
        echo ${{secrets.TEAMID}} | sed 's/./& /g'
